version: '3.7'

services:
  portfolioapi:
    image: portfolio-api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    # environment:
    #   NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
